const trucks = [
  {
    id: 1,
    name: "Ford F-150",
    type: "Pickup",
    manufacturer: "Ford",
    year: 2021,
    color: "Blue",
    engine: "3.5L V6",
    horsepower: 400,
    towingCapacity: "13,200 lbs",
    price: "$30,000",
  },
  {
    id: 2,
    name: "Chevrolet Silverado 1500",
    type: "Pickup",
    manufacturer: "Chevrolet",
    year: 2022,
    color: "Red",
    engine: "5.3L V8",
    horsepower: 355,
    towingCapacity: "11,500 lbs",
    price: "$32,000",
  },
  {
    id: 3,
    name: "Ram 1500",
    type: "Pickup",
    manufacturer: "Ram",
    year: 2023,
    color: "Black",
    engine: "3.0L V6 Diesel",
    horsepower: 260,
    towingCapacity: "12,750 lbs",
    price: "$35,000",
  },
  {
    id: 4,
    name: "Toyota Tacoma",
    type: "Mid-size Pickup",
    manufacturer: "Toyota",
    year: 2021,
    color: "White",
    engine: "3.5L V6",
    horsepower: 278,
    towingCapacity: "6,800 lbs",
    price: "$27,000",
  },
  {
    id: 5,
    name: "Nissan Titan",
    type: "Pickup",
    manufacturer: "Nissan",
    year: 2020,
    color: "Silver",
    engine: "5.6L V8",
    horsepower: 400,
    towingCapacity: "9,370 lbs",
    price: "$36,000",
  },
  {
    id: 6,
    name: "GMC Sierra 1500",
    type: "Pickup",
    manufacturer: "GMC",
    year: 2022,
    color: "Gray",
    engine: "6.2L V8",
    horsepower: 420,
    towingCapacity: "12,100 lbs",
    price: "$40,000",
  },
  {
    id: 7,
    name: "Honda Ridgeline",
    type: "Mid-size Pickup",
    manufacturer: "Honda",
    year: 2021,
    color: "Green",
    engine: "3.5L V6",
    horsepower: 280,
    towingCapacity: "5,000 lbs",
    price: "$35,000",
  },
  {
    id: 8,
    name: "Jeep Gladiator",
    type: "Mid-size Pickup",
    manufacturer: "Jeep",
    year: 2023,
    color: "Yellow",
    engine: "3.6L V6",
    horsepower: 285,
    towingCapacity: "7,650 lbs",
    price: "$45,000",
  },
  {
    id: 9,
    name: "Rivian R1T",
    type: "Electric Pickup",
    manufacturer: "Rivian",
    year: 2022,
    color: "Silver",
    engine: "Electric",
    horsepower: 750,
    towingCapacity: "11,000 lbs",
    price: "$67,500",
  },
  {
    id: 10,
    name: "Tesla Cybertruck",
    type: "Electric Pickup",
    manufacturer: "Tesla",
    year: 2023,
    color: "Matte Black",
    engine: "Electric",
    horsepower: 800,
    towingCapacity: "14,000 lbs",
    price: "$69,900",
  },
];

export { trucks };
